### ISSUE TITLE
dpkg-source error

### ISSUE THREAD

**Issue by dylanede** [NVIDIA/gdrcopy#107]
When trying to build a Debian package on Debian 10.3, I get this error message:
```text
dpkg-source: error: can't build with source format '3.0 (quilt)': non-native package version does not contain a revision
```
Apparently this means that the version of the package is not in the right form, i.e. `2.0` is not acceptable. I'm not sure what is acceptable though.

**Comment by drossetti** [comment]
@dylanede have you checked https://github.com/Tarsnap/tarsnap/issues/205 ?

**Comment by drossetti** [comment]
@dylanede were you able to work around your problem?
In case, could you please close this issue?

**Comment by drossetti** [comment]
no feedback. closing this issue
