### ISSUE TITLE
copylat is not in generated rpms

### ISSUE THREAD

**Issue by davidcarver** [NVIDIA/gdrcopy#108]
copylat is not in generated rpms

./tests/Makefile  and ./packages/gdrcopy.spec need to include copylat

**Comment by drossetti** [comment]
@davidcarver thanks for reporting this issue.

**Comment by cponder** [comment]
I don't see it in the source distribution, either:

      https://github.com/NVIDIA/gdrcopy/archive/v2.0.tar.gz

has these files in the tests subdirectory:

      Makefile  common.hpp  copybw.cpp  sanity.cpp

**Comment by drossetti** [comment]
@cponder thank you
@davidcarver the problem should have been addressed in the master branch. So either pick that one or wait for the next minor release.
