### ISSUE TITLE
Will you release a tag for 2.1 or do we have to use the v2_1 branch

### ISSUE THREAD

**Issue by bne86** [NVIDIA/gdrcopy#132]
question == subject.

**Comment by doctaweeks** [comment]
If 2.1 is a real version it should be tagged.

**Comment by drossetti** [comment]
@bne86  yes we are working at releasing v2.1 soon. 
We have just created a v2.1-beta1 release which is our current release candidate.

**Comment by drossetti** [comment]
release v2.1 is out, closing
