### ISSUE TITLE
how to install gdrcopy in docker container?

### ISSUE THREAD

**Issue by weberxie** [NVIDIA/gdrcopy#138]
Hi team,

I have installed gdrcopy in host,

the result of command 'ls -alh /dev/gdrdrv' in host is:
crw-rw-rw- 1 root root 230, 0 Sep 14 16:19 /dev/gdrdrv

but the result in container is:
ls: cannot access /dev/gdrdrv: No such file or directory

**Comment by drossetti** [comment]
@3XX0 do you have a quick recipe on how to pass a device inode (/dev/gdrdrv in this case) down to a docker container ?

**Comment by 3XX0** [comment]
For [enroot](https://github.com/nvidia/enroot) (and thus [pyxis](https://github.com/nvidia/pyxis)) this is done automatically, for Docker you would need to add `--device=/dev/gdrdrv:/dev/gdrdrv`

**Comment by drossetti** [comment]
@3XX0 thank you
@weberxie feel free to close the bug

**Comment by drossetti** [comment]
no feedback, closing
