### ISSUE TITLE
installtion on geforce 2080ti

### ISSUE THREAD

**Issue by dexhunter** [NVIDIA/gdrcopy#183]
Hi, just wonder is it possible to install this lib on a 2080ti cluster? Thanks

**Comment by pakmarkthub** [comment]
Hi @dexhunter ,

This library requires a hardware feature, which is available on Tesla and Quadro class GPUs. So, it would not work on your GeForce.

**Comment by dexhunter** [comment]
> Hi @dexhunter ,
> 
> This library requires a hardware feature, which is available on Tesla and Quadro class GPUs. So, it would not work on your GeForce.

ok thanks
