### ISSUE TITLE
gdrcopy deb dependency on gdrdrv-dkms is problematic for containers

### ISSUE THREAD

**Issue by cliffwoolley** [NVIDIA/gdrcopy#188]
In a container userspace, we would typically install the gdrcopy_*.deb (gdrapi), but _not_ gdrdrv-dkms.  Unfortunately, gdrcopy_*.deb has a dependency on the kernel-mode driver deb package.  While that's fine on bare metal, it doesn't really make sense for a containerized deployment.

The way CUDA handles this is to have `cuda-toolkit` and `cuda-drivers` packages that do not advertise any dependency on each other, and there is a `cuda` metapackage that depends on both for ease of installation.  Could we do something like that here?

**Comment by pakmarkthub** [comment]
The PR has been merged. Closing this issue.
