### ISSUE TITLE
use new CUDA 11.3 device attributes

### ISSUE THREAD

**Issue by drossetti** [NVIDIA/gdrcopy#189]
In CUDA 11.3, CU_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_SUPPORTED has been added.
Tracking here changes to deploy the new attribute where appropriate, as a minimum in the tests, for example to print a meaningful error message when running on a GPU without GPUDirect RDMA support.

The code should be compile time and run-time (as in CUDA enhanced) compatibile with previous CUDA releases.

**Comment by drossetti** [comment]
for example, one could use something like:
```
#if CUDART_VERSION >= 11030
cudaDriverGetVersion(&driverVersion);
if (driverVersion > 11030) {
  cudaDeviceGetAttribute(attr,
      cudaDevAttrGPUDirectRDMASupported, device);
  gdrdmaSupported = true;
}
#endif
```

**Comment by drossetti** [comment]
note that at the moment, libgdrapi does not have a dependency on libcuda, and it is not clear whether adding such dependency to call `cudaDeviceGetAttribute` is a good idea.
A compromise could be 1) to add that check in the test apps and 2) to document that the library does not explicitly check for GDR support and that users can run test apps to get appropriate diagnostic.

**Comment by pakmarkthub** [comment]
The PR has been merged. Closing this issue.
