### ISSUE TITLE
Question: will RTX 30 series with resizable BAR be supported?

### ISSUE THREAD

**Issue by bmerry** [NVIDIA/gdrcopy#196]
My understanding (which could well be wrong) is that the reason GPUDirect has been limited to Tesla/Quadro-class GPUs has been that GeForce GPUs only provide a 256MB BAR, which didn't allow for large chunks of GPU memory to be mapped into the system address space.

With NVIDIA now supporting resizable BAR on the RTX 30 series, will GPUDirect RDMA be possible on GPUs where that is correctly configured? (which I'm aware requires the right motherboard and BIOS and VBIOS and driver and phase of the moon).

**Comment by drossetti** [comment]
@bmerry Feel free to contact gpudirect@nvidia.com on these topics.
