### ISSUE TITLE
ioremap sometimes too slow

### ISSUE THREAD

**Issue by journey-wang** [NVIDIA/gdrcopy#20]
1. use nvidia_p2p_get_page get physical pages
2. use ioremap to map nvidia physical page to kernel virtual address
3. use memcpy_toio copy data from kernel to gpu
Sometimes memcpy_toio too slow, it costs 80ms to transfer 600KB data to gpu.
normally is 0.18ms.
4. when machine boots, it remains either be normal or slow until machine reboots.

Please help me! How to direct access nvidia physical memory from kernel module?

**Comment by drossetti** [comment]
@journey-wang just to clarify, is this issue regarding GDRcopy or a generic question?

**Comment by journey-wang** [comment]
@drossetti same to gdrcpy

**Comment by drossetti** [comment]
@journey-wang gdrcopy does not support kernel-level I/O on MMIO mapped GPU memory, hence I am closing this issue as not-a-bug
