### ISSUE TITLE
How to use gdrcopy in python?

### ISSUE THREAD

**Issue by pengpengSir** [NVIDIA/gdrcopy#230]
I need to transmit small data to GPU memory, like several KBs, how to use gdrcopy in python program?

**Comment by pakmarkthub** [comment]
Hi @pengpengSir ,

At the moment, GDRCopy does not support python. You may create your own python-c binding. It could introduce some overhead. You can benchmark and compare with using cudaMemcpy or other approaches.

By the way, what is your use case? Do you want GDRCopy for low latency or other proposes? Is your data in python or other representations -- e.g., in native numpy or panda?

**Comment by pakmarkthub** [comment]
Thank you for letting us know your use case. I will consult with the team and consider our future direction.

To leverage what we have today, you may want to go with CUDA Python first (https://developer.nvidia.com/blog/unifying-the-cuda-python-ecosystem/). I believe that it works with NumPy. Or you can try to create your own python wrapper for GDRCopy.
