### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by Dcn303** [NVIDIA/gdrcopy#250]
hi every one i am trying to install gdrcopy but i get this error as shown below 
please guide me through 
![image](https://user-images.githubusercontent.com/112604796/224031304-3d57f9f2-f6a3-4fc4-80f6-9239b9f275e7.png)
i have set the prefix as /home/urban/DL-workspace/gdrcopy-master
and CUDA as /opt/ohpc/pub/cuda/cuda-10.2

**Comment by pakmarkthub** [comment]
Hi @Dcn303,
The NVIDIA driver header files are missing. How did you install the NVIDIA driver? If you use package manager, did you install `sudo dnf module install nvidia-driver:latest-dkms` as stated in the README file?
