### ISSUE TITLE
GPUdirect

### ISSUE THREAD

**Issue by pyt-hnu** [NVIDIA/gdrcopy#252]
Can this driver be used for communication between FPGA and GPU

**Comment by pakmarkthub** [comment]
Hi @pyt-hnu,

The driver is designed for CPU-GPU communication. You can use it as base for developing your own FPGA-GPU driver. See more detail in [this page](https://docs.nvidia.com/cuda/gpudirect-rdma/).

**Comment by pyt-hnu** [comment]
> Can this driver be used for communication between FPGA and GPU

ok, thanks for your reply.
