### ISSUE TITLE
a question about memcpy in avx

### ISSUE THREAD

**Issue by hongbilu** [NVIDIA/gdrcopy#256]
for memcpy_uncached_store_avx and memcpy_cached_store_avx implementation, if source ptr is aligned, why memcpy_uncached_store_avx will copy 8*sizeof(__m256d) for every loop, but memcpy_cached_store_avx only copy 4*sizeof(__m256d), it that a empirical value?

**Comment by drossetti** [comment]
I am trying to recall... no good reason I believe.

**Comment by hongbilu** [comment]
thanks for truthful feedback.
