### ISSUE TITLE
How to understand the file "nv-p2p-dummpy.c" 

### ISSUE THREAD

**Issue by pyt-hnu** [NVIDIA/gdrcopy#282]
What is the purpose of the file "nv-p2p-dummy.c"?
why not to use the symbol of nvidia.ko?

**Comment by pakmarkthub** [comment]
Hi @pyt-hnu,

In the current design, we do not force users to install nvidia.ko before compiling gdrdrv.ko. For example, you can just have the nvidia header files ready without installing the nvidia driver. You can compile gdrdrv by `make NVIDIA_SRC_DIR=<path-to-nvidia-header>`. That is a reason why we have nv-p2p-dummy.

**Comment by pyt-hnu** [comment]
> Hi @pyt-hnu,
> 
> In the current design, we do not force users to install nvidia.ko before compiling gdrdrv.ko. For example, you can just have the nvidia header files ready without installing the nvidia driver. You can compile gdrdrv by `make NVIDIA_SRC_DIR=<path-to-nvidia-header>`. That is a reason why we have nv-p2p-dummy.

Thanks for your reply, Does this apply to all GPUDirect RDMA technologies?

**Comment by pakmarkthub** [comment]
No. Some drivers are in-tree with nvidia.ko or come with the same installation package as nvidia.ko. So, they have a better way of handling this issue. On the other hand, GDRCopy is off-tree with nvidia.ko. So, we need some workaround.
