### ISSUE TITLE
How should I implement device-to-device memory copying between different hosts?  For example, copying the contents from host B's  GPU memory to host A's CPU memory.

### ISSUE THREAD

**Issue by JOjoker-world** [NVIDIA/gdrcopy#300]

**Comment by pakmarkthub** [comment]
Hi @JOjoker-world,

This is internode communication. You can use a communication library such as MPI, NCCL, NVSHMEM, etc depending on the programming model your application is using.

**Comment by JOjoker-world** [comment]
Thank you very much for your reply. Do you mean that gdrcopy can achieve direct copying between GPU and CPU across different nodes (e.g., A.GPU -> B.CPU) by using the appropriate communication library?

**Comment by pakmarkthub** [comment]
No. GDRCopy is an intranode communication library between GPU and CPU. It cannot do internode communication. On the other hand, MPI, NCCL, NVSHMEM are designed to support internode communication. You will want to use them.

**Comment by JOjoker-world** [comment]
Alright, I understand. Thank you for your reply.
