### ISSUE TITLE
Can gdrcopy use in RCCL?

### ISSUE THREAD

**Issue by shanleo2024** [NVIDIA/gdrcopy#302]
HI, I wonder if the gdrcopy can be used in RCCL lib.
Can you give me some comments? thank you.

**Comment by AddyLaddy** [comment]
RCCL is an AMD product. NCCL is an Nvidia product. I suggest you ask your question on a RCCL forum.
However, I believe gdrcopy is not required on AMD GPUs.

**Comment by shanleo2024** [comment]
Thank you, and close this issue.
