### ISSUE TITLE
Failed tests (validate and copybw) with latest Mellanox driver and kernel

### ISSUE THREAD

**Issue by junjieqian** [NVIDIA/gdrcopy#34]
Hi, we found the tests break the machine with CUDA-9, Nvidia driver (390.25), latest Mellanox driver (v4_3-1_0_1_0) and Linux kernel (4.14.11). The installation of the gdrcopy finishes successfully, but the machine freezes and then reboots when running the tests.
any suggestions? Thanks

**Comment by lwdhw1987** [comment]
Hi, I got same problem on my machine, Have you addressed  this ? Is there any reason for this problem.

**Comment by drossetti** [comment]
did you solve this problem?

**Comment by junjieqian** [comment]
Hi, the issue still happens. The library is installed with ubuntu16.04 container and on host with coreOS (kernel version: 4.14.11). It is kind of impossible to grab any dump info, as the machine would freeze and then entering reboot loop.

**Comment by drossetti** [comment]
There are many ways to debug a kernel crash, for example see https://help.ubuntu.com/lts/serverguide/kernel-crash-dump.html

**Comment by drossetti** [comment]
besides, we need:
- a description of the HW, server/workstation make and model, cards installed
- a list of SW component
- a clear list of steps to reproduce

**Comment by drossetti** [comment]
@junjieqian I'll need an update on this or feel free to close this issue otherwise.
