### ISSUE TITLE
Support for fork

### ISSUE THREAD

**Issue by drossetti** [NVIDIA/gdrcopy#45]
today, forking could lead to spurious prints (https://github.com/NVIDIA/gdrcopy/blob/f54766b21d216584a6839340aa1ebf81a980b235/gdrdrv/gdrdrv.c#L236) and possibly a crash.
tracking here further investigations (a new unit test for this case) and possible mitigations (e.g. CLOEXEC when opening the driver fd).

**Comment by drossetti** [comment]
@pakmarkthub can you help with this?

**Comment by pakmarkthub** [comment]
Merged to the master branch. Closing this issue.
