### ISSUE TITLE
gdrcopy-devel RPM won't install

### ISSUE THREAD

**Issue by mrobbert** [NVIDIA/gdrcopy#48]
I have built the gdrcopy RPMS from the build_packages.sh script in the source tree and I've found that I'm unable to install the gdrcopy-devel package because it is missing a required dependency.

Error: Package: gdrcopy-devel-1.3-2.x86_64 (/gdrcopy-devel-1.3-2.x86_64)
           Requires: libgdrapi.so.1()(64bit)
The file listed was installed by the gdrcopy RPM, but that library didn't get listed as being provided by the RPM. 
If this works for other users then I may have messed something up in my environment, but if not it is probably a bug in the spec file that should get fixed. 
Either way I'm willing to put some work into figuring it out, but I wanted to know which side of the problem to focus on.

**Comment by drossetti** [comment]
right, it is a problem in the spec file.
In the past, I have not found a way to write it in such a way to work well for both RH6 and RH7.
If you figure it out, feel free to share the fix via a PR.

**Comment by drossetti** [comment]
BTW you can force the installation of the gdrcopy-devel package. 
Everything works because libgdrapi.so.1 is actually installed by gdrcopy.

**Comment by mrobbert** [comment]
I have created PR #53 that I believe fixes this issue.

**Comment by drossetti** [comment]
@pakmarkthub can you help with this?

**Comment by drossetti** [comment]
this issue has been actually been fixed, see https://github.com/NVIDIA/gdrcopy/pull/53#issuecomment-531387444
