### ISSUE TITLE
enforce ABI compatibility between user and kernel space components

### ISSUE THREAD

**Issue by drossetti** [NVIDIA/gdrcopy#67]
Currently there is no run-time ABI compatibility check between libgdrapi and gdrdrv. 

That can generate obscure errors, say in a container when libgdapi version A tries to work with baremetal gdrdrv version B.

A possible plan would be:
- to introduce the concept of ABI version in gdrdrv
- to add a new IOCTL to return that version to user-space
- in gdr_open(), check ABI compatibility

**Comment by pakmarkthub** [comment]
Merged the PR. 

Closing this issue.
