### ISSUE TITLE
provide a run-time version query mechanism

### ISSUE THREAD

**Issue by drossetti** [NVIDIA/gdrcopy#68]
We might consider a run-time query mechanism, like `gdr_query_version(int *major, int *minor)` or the more generic `gdr_get_attribute(int attr, int *value)`,  which would complement the dynamic link time mechanism offered by ld.so.

That would be especially useful, say in MPI libraries, when dynamically loading the library with `dlopen("libgdrapi.so")` and resolving symbols with `dlsym()`, to enforce a run-time compatibility check.

**Comment by pakmarkthub** [comment]
The PR has been merged. Close this issue
